# Apriori Algorithm

Apriori algorithm is given by R. Agrawal and R. Srikant in 1994 for finding frequent itemsets in a dataset for boolean association rule. Name of the algorithm is Apriori because it uses prior knowledge of frequent itemset properties. We apply an iterative approach or level-wise search where k-frequent itemsets are used to find k+1 itemsets.

To improve the efficiency of level-wise generation of frequent itemsets, an important property is used called Apriori property which helps by reducing the search space.

*Apriori Property* â€“
All non-empty subset of frequent itemset must be frequent. The key concept of Apriori algorithm is its anti-monotonicity of support measure. Apriori assumes that

>All subsets of a frequent itemset must be frequent(Apriori propertry). If an itemset is infrequent, all its supersets will be infrequent.

Before we start understanding the algorithm, go through some definitions which are explained in my previous post.
Consider the following dataset and we will find frequent itemsets and generate association rules for them.



**PYTHON IMPLEMENTATION:MLEXTEND**

In [15]:
dataset = [
    ['French Fry', 'Burger', 'Nutmeg', 'Cheese', 'Cola', 'Noodles'],
    ['French Fry', 'Apple', 'Cheese', 'Cola'],
    ['French Fry', 'Unicorn', 'Corn', 'Cheese', 'Noodles'],
    ['Dill', 'Burger', 'Nutmeg', 'Cheese', 'Cola', 'Noodles'],
    ['French Fry', 'Apple', 'Cheese', 'Cola'],
    ['Dill', 'Burger', 'Nutmeg', 'Cheese', 'Cola', 'Noodles'],
    ['French Fry', 'Apple', 'Cheese', 'Cola'],
    ['French Fry', 'Unicorn', 'Corn', 'Cheese', 'Noodles'],
    ['Dill', 'Burger', 'Nutmeg', 'Cheese', 'Cola', 'Noodles'],
    ['French Fry', 'Apple', 'Cheese', 'Cola'],
    ['Corn', 'Burger', 'Burger', 'Cheese', 'Ice cream', 'Cola']
]

dataset

[['French Fry', 'Burger', 'Nutmeg', 'Cheese', 'Cola', 'Noodles'],
 ['French Fry', 'Apple', 'Cheese', 'Cola'],
 ['French Fry', 'Unicorn', 'Corn', 'Cheese', 'Noodles'],
 ['Dill', 'Burger', 'Nutmeg', 'Cheese', 'Cola', 'Noodles'],
 ['French Fry', 'Apple', 'Cheese', 'Cola'],
 ['Dill', 'Burger', 'Nutmeg', 'Cheese', 'Cola', 'Noodles'],
 ['French Fry', 'Apple', 'Cheese', 'Cola'],
 ['French Fry', 'Unicorn', 'Corn', 'Cheese', 'Noodles'],
 ['Dill', 'Burger', 'Nutmeg', 'Cheese', 'Cola', 'Noodles'],
 ['French Fry', 'Apple', 'Cheese', 'Cola'],
 ['Corn', 'Burger', 'Burger', 'Cheese', 'Ice cream', 'Cola']]

In [16]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder

In [17]:
!pip install mlxtend

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mlxtend in c:\program files\python310\lib\site-packages (0.19.0)
Requirement already satisfied: scipy>=1.2.1 in c:\program files\python310\lib\site-packages (from mlxtend) (1.7.3)
Requirement already satisfied: setuptools in c:\program files\python310\lib\site-packages (from mlxtend) (57.4.0)
Requirement already satisfied: joblib>=0.13.2 in c:\program files\python310\lib\site-packages (from mlxtend) (1.1.0)
Requirement already satisfied: pandas>=0.24.2 in c:\program files\python310\lib\site-packages (from mlxtend) (1.3.4)
Requirement already satisfied: matplotlib>=3.0.0 in c:\program files\python310\lib\site-packages (from mlxtend) (3.5.0)
Requirement already satisfied: numpy>=1.16.2 in c:\program files\python310\lib\site-packages (from mlxtend) (1.21.4)
Requirement already satisfied: scikit-learn>=0.20.3 in c:\program files\python310\lib\site-packages (from mlxtend) (1.0.1)
Requirement already satisfied: cycler>=0.10 in c:\program files\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\program files\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.28.2)
Requirement already satisfied: pillow>=6.2.0 in c:\program files\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (8.4.0)
Requirement already satisfied: setuptools-scm>=4 in c:\program files\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (6.3.2)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\program files\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\program files\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in c:\program files\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.6)
Requirement already satisfied: packaging>=20.0 in c:\program files\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (21.3)
Requirement already satisfied: pytz>=2017.3 in c:\program files\python310\lib\site-packages (from pandas>=0.24.2->mlxtend) (2021.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\program files\python310\lib\site-packages (from scikit-learn>=0.20.3->mlxtend) (3.0.0)
Requirement already satisfied: six>=1.5 in c:\program files\python310\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)
Requirement already satisfied: tomli>=1.0.0 in c:\program files\python310\lib\site-packages (from setuptools-scm>=4->matplotlib>=3.0.0->mlxtend) (1.2.2)

In [18]:
te=TransactionEncoder()
te_ary=te.fit(dataset).transform(dataset)

In [19]:
df = pd.DataFrame(te_ary,columns=te.columns_)
df

,Apple,Burger,Cheese,Cola,Corn,Dill,French Fry,Ice cream,Noodles,Nutmeg,Unicorn
0,False,True,True,True,False,False,True,False,True,True,False
1,True,False,True,True,False,False,True,False,False,False,False
2,False,False,True,False,True,False,True,False,True,False,True
3,False,True,True,True,False,True,False,False,True,True,False
4,True,False,True,True,False,False,True,False,False,False,False
5,False,True,True,True,False,True,False,False,True,True,False
6,True,False,True,True,False,False,True,False,False,False,False
7,False,False,True,False,True,False,True,False,True,False,True
8,False,True,True,True,False,True,False,False,True,True,False
9,True,False,True,True,False,False,True,False,False,False,False
10,False,True,True,True,True,False,False,True,False,False,False

In [20]:
from mlxtend.frequent_patterns import apriori 
frequent_itemsets=apriori(df,min_support=0.6,use_colnames=True)
frequent_itemsets

    support              itemsets
0  1.000000              (Cheese)
1  0.818182                (Cola)
2  0.636364          (French Fry)
3  0.818182        (Cheese, Cola)
4  0.636364  (Cheese, French Fry)

# Association Rule Mining

In [21]:
from mlxtend.frequent_patterns import association_rules
res=association_rules(frequent_itemsets,metric='confidence',min_threshold=0.7)
res

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Cheese),(Cola),1.000000,0.818182,0.818182,0.818182,1.0,0.0,1.0
1,(Cola),(Cheese),0.818182,1.000000,0.818182,1.000000,1.0,0.0,inf
2,(French Fry),(Cheese),0.636364,1.000000,0.636364,1.000000,1.0,0.0,inf

In [22]:
res1=res[['antecedents','consequents','support','confidence','lift']]
res1

    antecedents consequents   support  confidence  lift
0      (Cheese)      (Cola)  0.818182    0.818182   1.0
1        (Cola)    (Cheese)  0.818182    1.000000   1.0
2  (French Fry)    (Cheese)  0.636364    1.000000   1.0

In [23]:
res2=res1[res1['confidence']>=1]
res2

    antecedents consequents   support  confidence  lift
1        (Cola)    (Cheese)  0.818182         1.0   1.0
2  (French Fry)    (Cheese)  0.636364         1.0   1.0